### ISSUE TITLE
Submission Checklist

### ISSUE THREAD

**Issue by StreamOfMaya** [Zondax/ledger-tezos#11]
**Submission checklist** 

- [ ] 2 Icons (for Ledger device and Ledger Manager) 
- [ ] Companion app (binaries or package for Windows/MacOS/Linux) 
- [ ] Contact information 
- [ ] Link to tutorial hosted on third party website 
- [ ] Video of your application running on the Ledger device

:link: [zboto Link](https://app.clickup.com/t/8692qbgbz)
