### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by becominginsane** [Zondax/ledger-tezos#170]
These tasks are general minor improvements

- [ ] ParseError not idiomatic rust
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/handlers/parser_common.rs#L11

- [ ] Determine that `proto` is being used for in `BlockData` when parsing
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/baking.rs#L118

- [ ] Determine what to do with `tag` in `EndorsementData`
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/baking.rs#L31

- [ ] Don't hardcode addr hash but instead derive from public key
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/handlers/public_key.rs#L347

## Tasks that are blocked

These tasks result blocked, mostly for lack of spec

- [ ] JSON format for `Double Endorsement Evidence` operation
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/endorsement.rs#L333

- [ ] `Double Endorsement Evidence` parser unit test
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/endorsement.rs#L389

- [ ] JSON format for `Double Baking Evidence` operation
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/double_baking_evidence.rs#L251

- [ ] JSON format for `Failing Noop` operation
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/failing_noop.rs#L105

- [ ] Signatures in `Endorsement`-style operations (json, binary and display format)
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/endorsement.rs#L256
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/endorsement.rs#L189
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/endorsement.rs#L231

## Possibly out of scope

- [ ] JSON format for `Script` in `Origination` operations
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/origination.rs#L306

- [ ] JSON format for michelson code in `Transfer` operation parameters
https://github.com/Zondax/ledger-tezos/blob/ef4425540c7425b359e4112c52e07f4520207765/rust/app/src/parser/operations/transfer.rs#L464
